### ISSUE TITLE
Enchanted raw materials prices don't get updated

### ISSUE THREAD

**Issue by alcakd** [broderickhyman/albiondata-client#10]
I've been running the data client and scanning to update various 4.x resources. The console reports that it's uploading the market orders but Albion2d DB doesn't show the prices.

Example:
https://www.albiononline2d.com/en/item/id/T4_HIDE_LEVEL1

**Comment by broderickhyman** [comment]
Is this working for you now?

**Comment by zeromic** [comment]
This Item has still no Market Values on its page:
https://www.albiononline2d.com/en/item/id/T4_HIDE_LEVEL1
but the category shows some:
https://www.albiononline2d.com/en/item/cat/resources/subcat/hide?tier=4&enchantment=0
maybe its a website bug?

**Comment by alcakd** [comment]
Interesting, it looks like it is just a website UI issue then. I'll close this issue, thanks!
