### ISSUE TITLE
Enchanted Resources price is not updating

### ISSUE THREAD

**Issue by Babbaji** [broderickhyman/albiondata-client#105]
I've tried calling the api after updating the prices, (opening the market in thetford with albion data client open, it even said the usual "ingesting offers" log)
https://www.albion-online-data.com/api/v1/stats/prices/T5_HIDE_LEVEL1 returns all the prices at 0 for Thetford and any other city as well.

**Comment by GalexyN** [comment]
Any reason why youre using v1 when the api is on v2?

Also please see that the api uses keys from this dump - https://github.com/broderickhyman/ao-bin-dumps

In v2 the api call for your uncommon hide would be 
`https://www.albion-online-data.com/api/v2/stats/Prices/T5_HIDE_LEVEL1@1.json?locations=Thetford`

Making that call returns me a json for Thetford 5.1 hides which looks like theres only 1 being sold

response: 
```
[
    {
        "item_id": "T5_HIDE_LEVEL1@1",
        "city": "Thetford",
        "quality": 1,
        "sell_price_min": 683,
        "sell_price_min_date": "2022-02-21T08:05:00",
        "sell_price_max": 698,
        "sell_price_max_date": "2022-02-21T08:05:00",
        "buy_price_min": 652,
        "buy_price_min_date": "2022-02-21T09:00:00",
        "buy_price_max": 652,
        "buy_price_max_date": "2022-02-21T09:00:00"
    }
]
```
