### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SmokeyBear11** [broderickhyman/albiondata-client#116]
when i run the client it says pain and it is not working how can I fix this?
<img width="916" alt="Screen Shot 2022-07-03 at 3 08 29 AM" src="https://user-images.githubusercontent.com/108605657/177029114-13d5af28-188c-46ea-b98c-21e84708e3ff.png">

**Comment by sxe** [comment]
Start it with sudo on linux. Worked for me.
