### ISSUE TITLE
Program can't tell the difference between High and Low Sell Orders.

### ISSUE THREAD

**Issue by KillerXtreme-** [broderickhyman/albiondata-client#12]
This issue was talked about in discord and I figured I'd add it to the list of issues in case someone wanted to tackle it. The problem is that the program can't tell the difference when a player loads their marketplace and has their price sorting from High to Low. If a player has their sorting from High to Low when updating the database it will take the highest price on that page and think it's actually the sell_price_min. Making the database wrong and relaying the Highest price as the Lowest price.

For instance the current Price as I write this for itemID="T1_FACTION_FOREST_TOKEN_1" with location "Caerleon" returns with sell_price_min="52999999" while in game the actual sell_price_min should = 74995. When you set the marketplace to sort high to low you see it's picking up that first number as the low price.

Either some sort of filter needs to be added to filter those out, or some sort of check to make sure the number doesn't end up being more than 2x the price or there abouts.

**Comment by broderickhyman** [comment]
Update: I have a solution architected, not sure when I will be able to get it written into the client.

**Comment by devkao** [comment]
you could use the preceding "AuctionGetOffers" Request Object to track the applied sorting and reuse that information in the reponse.

Sample JSON:
`{"0":4,"1":"","2":"","3":"","4":0,"5":"","6":[2795,2796,...],"7":0,"8":"","9":50,"11":1,"12":true,"253":74}`

the field of interest is in 11. This field tells the server what to order the items by.
after checking several scenario you can use the following values :

0 -> order by price ascending  
 1 -> order by price descending
 2 -> order by Duration ascending
 3 -> order by Duration descending
 4 -> order by name ascending
 5 -> order by name descending

**Comment by broderickhyman** [comment]
Yup, that was the idea, thanks for getting field 11, I added it to the wiki page
