### ISSUE TITLE
Join operation not parsing correctly

### ISSUE THREAD

**Issue by rsxdalv** [broderickhyman/albiondata-client#14]
Hi, even after 3 restarts (including game and client) I'm still getting this error:
The player name or id has not been set. Please restart the game and make sure the client is running.

**Comment by broderickhyman** [comment]
Has the client worked for you in the past or have you always had this issue?

**Comment by rsxdalv** [comment]
Never has the client been able to intercept the onJoin packet, the only thing I can do is get location set by changing areas

**Comment by broderickhyman** [comment]
Yes, that is how most people set the location. From the code it looks like you are getting the player name error because you are using a private uploader?

**Comment by rsxdalv** [comment]
Yes

**Comment by broderickhyman** [comment]
@rsxdalv This isn't fixed yet but you shouldn't see the error message on the latest version of the client.
