### ISSUE TITLE
Crashing when can't find the device specified

### ISSUE THREAD

**Issue by Uriei** [broderickhyman/albiondata-client#15]
Just that, I start it, and it stays running for a while until it decides to close itself or it just closes after a few seconds, no error messages or anything, does it save a log anywhere to check?

EDIT: I've done some digging and I've found the -debug argument, and also ran it from a terminal and I got this:
`Error opening adapter: The system cannot find the device specified. (20)`
and I've seen that it dies when it tries to read from one of the network adapters that Docker installs, to be precise the one named "vEthernet (Default Switch)", I don't know if this identifier will help or it's a random generated one on each PC, but the device identifier that crashes it is
`\Device\NPF_{4B78D377-81BB-4E0E-A302-D6362F3F1487}`

**Comment by broderickhyman** [comment]
Thank you. Devs should do the following:
1. Check if device id is standard and ignore it like the other adapters if it is
1. Handle the error better so that it doesn't crash

**Comment by Squirrelius** [comment]
Yeah, got the same problem. It's a shame :(

**Comment by broderickhyman** [comment]
@Squirrelius Are you having a can't find device issue, or it was just automatically closing?

**Comment by kywan** [comment]
i got same but in french
```
FATA[2019-08-10T17:53:52+02:00] Error opening adapter: Le p�riph�rique sp�cifi� est introuvable. (20)
```

**Comment by josehdotech** [comment]
This is still happening, the client is crashing after the error, but it seems to be happening when you install Wincap and did not reboot  the computer, the adapter installed by wincap cant start normally and the client crashes.

**Comment by vladverbiy** [comment]
> 
> 
> Just that, I start it, and it stays running for a while until it decides to close itself or it just closes after a few seconds, no error messages or anything, does it save a log anywhere to check?
> 
> EDIT: I've done some digging and I've found the -debug argument, and also ran it from a terminal and I got this:
> `Error opening adapter: The system cannot find the device specified. (20)`
> and I've seen that it dies when it tries to read from one of the network adapters that Docker installs, to be precise the one named "vEthernet (Default Switch)", I don't know if this identifier will help or it's a random generated one on each PC, but the device identifier that crashes it is
> `\Device\NPF_{4B78D377-81BB-4E0E-A302-D6362F3F1487}`

you need to reinstall winpcap

**Comment by haggen** [comment]
Fixed by installing https://npcap.com/#download instead.
