### ISSUE TITLE
Save and Replay Operations for Development Testing

### ISSUE THREAD

**Issue by broderickhyman** [broderickhyman/albiondata-client#16]
Save off the photon packets into a file in the order they are received. Then have the ability to read them back in for testing during development.

**Comment by regner** [comment]
The client already supports processing offline pcap files. I suppose this would make it easier potentially, but seems pretty low priority when the functionality is already there.

**Comment by broderickhyman** [comment]
How would your average user create a pcap file in order to submit a bug? With this way they can easily add a command line argument and save off a file using the client, that the client could then parse and replay.
Also I am not saving the literal operations, I am saving the photon commands. Which you have a point, they could be processed poorly, but since they are at a fairly base level the risk there should be minimal.
Anyway, the work was pretty simple and has already been done it’s just not in the master branch yet. I could potentially refactor it if the need arises to instead save raw packets instead of the commands.

**Comment by broderickhyman** [comment]
Released
