### ISSUE TITLE
Make minimization more intuitive

### ISSUE THREAD

**Issue by broderickhyman** [broderickhyman/albiondata-client#24]
Currently everyone's window minimizes, many people don't realize it is happening. I believe it was created this way to help people always have it running but it is confusing people. Maybe make it a config setting or something.

**Comment by josehdotech** [comment]
This can be marked as solved on the version 0.0.22, isn't it?

**Comment by broderickhyman** [comment]
Yup, thanks for reminding me! I haven't looked at these in a while, it's just been in my head!
