### ISSUE TITLE
"Error while sending ingest to nats with data: nats: invalid connection"

### ISSUE THREAD

**Issue by HIMix** [broderickhyman/albiondata-client#33]
After installing and running Albion Data Client my friend have this error in console:

> ERRO[2019-07-30T16:37:07+02:00] Error while sending ingest to nats with data: nats: invalid connection

Any ideas how this may be fixed?
Thanks.

**Comment by Tauranis** [comment]
Me too

**Comment by Major401** [comment]
Is this ever going to be fix?

**Comment by broderickhyman** [comment]
@Major401 I haven't been able to reproduce it, are you sure you are using the correct and latest client?

**Comment by broderickhyman** [comment]
This could also be an issue with BitDefender anti-virus, can you confirm if you have it installed?

**Comment by yangjiguang1992** [comment]
ERRO[2021-05-23T21:19:19-07:00] Error while sending ingest to nats with data: nats: invalid connection'
I'm having the same issue, and I am using the newest client without any defenders,

**Comment by MennoVink** [comment]
I've recently started experiencing this issue too, thing is that the program did work correctly before. What kind of information would you need? Pinging www.albion-online-data.com already times out everything

**Comment by HIMix** [comment]
> This could also be an issue with BitDefender anti-virus, can you confirm if you have it installed?

Exactly!!!
Thanks for suggestion, I'll check later how can I fix it on my side 👍

**Comment by blind-reaper** [comment]
I cant seem to connect either

```
nslookup www.albion-online-data.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
www.albion-online-data.com	canonical name = albion-online-data.com.
Name:	albion-online-data.com
Address: 162.243.14.70
```

> telnet 162.243.14.70 4222
> Trying 162.243.14.70...

Cannot connect via telnet, cannot ping IP.

I'm using linux without firewall or AV.

**Comment by Tiaryn** [comment]
@broderickhyman posted on the discord server: Someone or some people hammered the server with new data and it capped at 100% CPU load. Broderick turned off new data and set it to read only (data from 12th May) until he's got the time to take a deeper look at it.
You probably need to set up a private server to ingest data in the mean time.

**Comment by coingraham** [comment]
@Tiaryn two quick questions.  Is there a walkthrough on setting up a private server?

**Comment by Qemickl** [comment]
Same problem. Win10 whithout any AV

**Comment by HIMix** [comment]
> Same problem. Win10 whithout any AV

read comments above, there are global problems with server at the moment

**Comment by HIMix** [comment]
Closing this issue as irrelevant since (as I guess) the root of my problem was this global problem with albion-online-data.com

Anyone facing this issue should track _announcements_ channel at discord server
Last update from @broderickhyman at the moment:
> I have rolled back the server to May 12th and shut down all new data until we figure out what we are going to do. This will at least allow the existing history data to be available and for people to be able to download the database dumps
[link to this meesage at discord server](https://discord.com/channels/336216450689794048/545608962930638868/845869782284501013)
