### ISSUE TITLE
.Net Core Client

### ISSUE THREAD

**Issue by broderickhyman** [broderickhyman/albiondata-client#35]
Many people have expressed concern with working with golang, and it is confirmed by StackOverflow that it is a lower percentage of the developer population that know how to code it.
Also, making it .Net would allow us to decompile pieces of the game client and copy into the project as we need, increasing productivity.

**Comment by kendinikertenkelebek** [comment]
what do you think about linux or macos users in this case?

**Comment by rbnswartz** [comment]
.net core is cross platform so linux and macos users would still be able touse it

**Comment by raspher** [comment]
What about rust? It's most loved language on stackoverflow and it's popularity (from SO) it's only 6 times lower. 

System architecture
Well, as we all experienced, actual centralized architecture and design tends to overload the server. Dealing with a lot of data produces high load. One of solutions is a distributed system (which can be implemented in C# as well). In such scenario servers (supernodes) will mostly verify data from clients. Data would be downloaded from servers and stored in sqlite (which works well with even hundreds of gigabytes). Data is downloaded on requests.

Channels
Historical data on separate, last prices on separate. There are a lot of reasons, but maybe i am wrong with it.

Tech stack
We can all do in C#, but languages with garbage collector are generally slower. There is always C/C++, which is awfull in my opinion. Rust seems (for me) that one which we should go with. 

Distributed systems needs threads, they should be well managed to handle load and processes with high priority (e.g. transmitting existing data over processing new data). If we care enough, such system should be lightweight and designed to run as a deamon. We shouldn't feel it's running. It should be the reason to avoid Java (ram hungry), Go (lack of threads) and others system which doesn't fill requirements.

My proposal:
- distributed
- rust
- sqlite
- binary protocol for transmitting data
- hey, data is on my own machine, it can be accessible from file or via http

If there would be millions of players, with this design, there would be no downtime.



Please share your viewpoint, ideas or criticism as well 🙂

**Comment by broderickhyman** [comment]
@raspher First off, the recent issues are not because of the architecture or the language, it is because of malicious actors flooding the service with bad information, and the service had no security at all.
Second, you can’t just say it is “only 6 times lower”, that means it has millions less developers. This is an open source project and thus needs as many potential developers as possible. To date I am basically the only developer in recent years even though I’m using one of the more common languages.

For others that are wondering what we are referencing from StackOverflow survey:
https://insights.stackoverflow.com/survey/2020#technology-programming-scripting-and-markup-languages
