### ISSUE TITLE
idea: trigger local NVidia shadowplay / OBS instant replay recording on Events

### ISSUE THREAD

**Issue by jeske** [broderickhyman/albiondata-client#38]
The albion client is in a position to know that a player experienced a "notable" event..

Player died, got a player kill, got a very valuable loot item, etc....

It would be awesome to be able to use these events to automatically trigger NVidia shadowplay and/or OBS to save their instant replay buffer.

While this may seem outside the core goal of data collection.. this would be a really awesome feature that would drive many users to want the client.. which would in turn mean more users are collecting and uploading data.

**Comment by walkeralencar** [comment]
this blows my mind sometimes too but needs a few other knowledges about shadowplay, that I don't have, but can be a cool feature to try
