### ISSUE TITLE
3 new Blackzone auction houses added

### ISSUE THREAD

**Issue by Triky313** [broderickhyman/albiondata-client#40]
As of today there are 3 new auction houses in the Blackzone.
Can they be added?

**Comment by broderickhyman** [comment]
What are the names of the cities the auction houses are in?

**Comment by Triky313** [comment]
The 3 new Outland outposts are called:

Merlyn's Rest (Forest Biome)
Arthur's Rest (Snow Biome)
Morgana's Rest (Swamp Biome)

**Comment by broderickhyman** [comment]
@Triky313 This has been added, you can search for them with the api via
ArthursRest
MerlynsRest
MorganasRest
