### ISSUE TITLE
Market prices do not update

### ISSUE THREAD

**Issue by eduardozf** [broderickhyman/albiondata-client#41]
Why market prices don't update?
![image](https://user-images.githubusercontent.com/42107537/72751318-1451d400-3b9e-11ea-98a4-c7f7bc252877.png)

I remember old versions that showed a message when open any market, i think may be related
![image](https://user-images.githubusercontent.com/42107537/72751375-3cd9ce00-3b9e-11ea-8227-9a40d962d7c5.png)

**Comment by Aerics84** [comment]
The problems are the new event codes which are needed to analyse the packets correctly. I don`t know where to extract them from the client.

**Comment by broderickhyman** [comment]
Yes, I know what the problem is, this literally just launched, give me some time to update it, I do have a day job.

**Comment by eduardozf** [comment]
Sorry, take your time!

**Comment by broderickhyman** [comment]
Since it seems that there are a lot of people coming back for this update I was able to quickly push out the fix, your client should update automatically.

**Comment by Aerics84** [comment]
> Since it seems that there are a lot of people coming back for this update I was able to quickly push out the fix, your client should update automatically.

Can you please give me a hint where i can find the event codes?

**Comment by broderickhyman** [comment]
@Aerics84 It is already fixed

**Comment by Aerics84** [comment]
@broderickhyman I`m just interested as a developer how/where to extract this data :)

**Comment by broderickhyman** [comment]
It comes from their source code when decompiled

**Comment by Aerics84** [comment]
@broderickhyman Which file are you looking at? At the bin or assets files? Or do you mean decompile executeables? I don`t think so.
I already decrypt the bin files for the new mobs and resources. But can´t find the event codes anywhere :(

**Comment by broderickhyman** [comment]
@Aerics84 The dll files are the source code, in your decompiler you should be able to search for operationcodes. Also I have all the bin files decrypted at https://github.com/broderickhyman/ao-bin-dumps.
If you have more questions like this it would probably be better to use the discord channel listed on the website
