### ISSUE TITLE
Property Name Casing

### ISSUE THREAD

**Issue by Triky313** [broderickhyman/albiondata-client#42]
I had to change the property name several times e.g.
[JsonProperty (PropertyName = "buy_price_max_date")]
[JsonProperty (PropertyName = "buyPriceMaxDate")]
Is buy_price_max_date correct now?

**Comment by broderickhyman** [comment]
I upgraded the api to .Net Core 3 last night and it changed to camelCase. I fixed the issue this morning and the correct casing is snake_case
