### ISSUE TITLE
Improve verbosity  to DEBUG

### ISSUE THREAD

**Issue by walkeralencar** [broderickhyman/albiondata-client#43]
using **_go generate_**, its possible improve verbosity on DEBUG adding event or operation name:
https://github.com/broderickhyman/albiondata-client/blob/a033e1d50ce685b8c23c3e803deef438c6b5802e/client/listener.go#L208

overwrite line with
``log.Debugf("EventDataType: [%v]%v - %v", params[252].(int16), EventType(params[252].(int16)), params)``

the result:
![unknown](https://user-images.githubusercontent.com/459481/74117167-88780a00-4b95-11ea-8371-47308c36bb8d.png)

**Comment by broderickhyman** [comment]
Thanks for the help, this is getting released in 0.0.26
