### ISSUE TITLE
The new Blackzone auction house names are currently codes in history result

### ISSUE THREAD

**Issue by Triky313** [broderickhyman/albiondata-client#44]
The new Blackzone auction house names are currently codes e.g. 3004, can that be adjusted?

In api/v2/stats/history result

Here a example: https://www.albion-online-data.com/api/v2/stats/history/T4_LEATHER?locations=3004&date=2-10-20&qualities=1&time-scale=24

**Comment by broderickhyman** [comment]
When looking in world.xml I see that 3004 is Martlock. I have already added:
MorganasRest = 8
MerlynsRest = 1012
ArthursRest = 4300
Example: https://www.albion-online-data.com/api/v2/stats/history/T4_BAG?locations=MorganasRest&time-scale=24
