### ISSUE TITLE
How to download client on MacOS?

### ISSUE THREAD

**Issue by aussio** [broderickhyman/albiondata-client#48]
Hey there!

It seems from /scripts that you are producing builds for Windows, Mac, and Linux, but I'm unable to figure out how to use any of the resources provided [in the releases](https://github.com/broderickhyman/albiondata-client/releases).

Could you provide some instructions for me please? I would be open to instructions on how to set up the Go project and build it myself as well if that's easier.

`update-darwin-amd64.gz` contains only a single file when unzipped with no file extension. Changing the extension to either .pkg or .app both do not work in attempting to get Mac to recognize what to do with the file. I played with those in case this file was meant to be the Mac installer.

**Comment by aussio** [comment]
Ah, I figured it out! I'll add a PR to the README later in the week. Until then, or in case I forget:

1. Download the latest `update-darwin-amd64.gz` file from [the Releases page](https://github.com/broderickhyman/albiondata-client/releases)
2. Unzip that file from the Finder or with `gunzip update-darwin-amd64.gz`
3. The unzipped `update-darwin-amd64` file is a Golang binary file. You'll need to make this file executable so it can be run directly. You can do this from your Terminal with: `chmod +x update-darwin-amd64`
4. Run the client from your Terminal with `./update-darwin-amd64` and you should see output similar to the following if successful:
![image](https://user-images.githubusercontent.com/6733176/79049202-2026c280-7bf0-11ea-864f-e90a8123d770.png)

**Comment by broderickhyman** [comment]
Thanks for the markdown, I put it in the readme
