### ISSUE TITLE
Could you please explain a bit how to put everything to work together?

### ISSUE THREAD

**Issue by elboletaire** [broderickhyman/albiondata-client#5]
Hi! I've been trying to setup the albion api locally, to be able to make some changes to it, but I'm failing when setting up the deduper.

After setting up the client and having it running, when I try to execute the deduper it's not able to connect to the client.

Note that I'm a bit newbie to golang, so I may be missing something, that's why I'm asking for a better documentation on how to get everything running.

Thanks in advance, and thanks for maintain this project and sharing it to us :)

PS. I'm interested in creating some market charts, and for that I'll need information that I don't see listed anywhere, like lists of markets and products (I've seen in the api some view and stats methods, but nothing about listing contents).

**Comment by broderickhyman** [comment]
The deduper and the client do not connect directly, but indirectly through the nats server. I could go into more detail but I don't think that is what you need.

If you are just interested in the api, you technically only need albiondata-api and albiondata-sql (No need for the deduper as I am running that on the main server)

Also, if you are not already on the [Discord](https://discord.gg/ndXcxUf) you should join as most discussion happens there. Someone already put some [basic google doc charts together].(https://docs.google.com/spreadsheets/d/1bZWuAf0pKupLY6kNZreewxqkyDJiLhT4A4iM1SbNQcs/edit?usp=sharing)

**Comment by elboletaire** [comment]
Apparently, the readme from [albiondata-api][] confounded me, because it says::

> The API to access the data imported by albiondata-sql from albiondata-client over albiondata-deduper.

Anyway, thanks for the answer. I'll join the discord channel when at home, and If I have more doubts I'll ask there.

BTW, I still think that this info should be in a readme or wiki here in github :sweat_smile: .

[albiondata-api]: https://github.com/broderickhyman/albiondata-api
