### ISSUE TITLE
Request/Question

### ISSUE THREAD

**Issue by AlexisGeorgiou** [broderickhyman/albiondata-client#50]
So I checked out the project and I wanted to ask if there is something I could find online related to this. I didn't know where to ask since nobody is into albion online stuff and I just start to search stuff.
I was wondering if there is somewhere info list of all players online in the albion world with probably their guild name info too. Like Having two columns with character name and his guild name or maybe even more stuff.

Is this even possible? Since I have understanded that the game doesn't share much information.

**Comment by broderickhyman** [comment]
I haven't heard of this anywhere. If you have more questions we have a discord channel for collaboration.
