### ISSUE TITLE
Queen Patch 11 Client not identifying zone

### ISSUE THREAD

**Issue by Pasimega** [broderickhyman/albiondata-client#52]
Ever since the Queen Patch 11 hit 05.05.20 the client does not identify the zone anymore making it unable to update market data.

Console output when trying to update market data:

INFO[2020-05-05T15:09:10+02:00] Starting Albion Data Client, version: 0.0.27
INFO[2020-05-05T15:09:10+02:00] This is a third-party application and is in no way affiliated with Sandbox Interactive or Albion Online.
INFO[2020-05-05T15:09:10+02:00] Additional parameters can listed by calling this file with the -h parameter.
INFO[2020-05-05T15:12:50+02:00] Watching Albion process with PID "14972"...
ERRO[2020-05-05T15:22:10+02:00] The players location has not yet been set. Please transition zones so the location can be identified.
ERRO[2020-05-05T15:24:51+02:00] The players location has not yet been set. Please transition zones so the location can be identified.
ERRO[2020-05-05T15:24:57+02:00] The players location has not yet been set. Please transition zones so the location can be identified.

**Comment by rbnswartz** [comment]
Same thing happens for me. Looks like it isn't noticing location changes.

**Comment by jppaterno** [comment]
happens to me too. I hope this will be fixed soon. Might do some investigating too. thanks!

**Comment by magica5** [comment]
Same here - looks like the big patch has changed where to pull the location information.

**Comment by czakalw3** [comment]
It's a parsing error that occurs during location changes, due to a datatype mismatch. Author can fix it easily.

**Comment by broderickhyman** [comment]
This should be fixed in release 0.0.28
