### ISSUE TITLE
Buy Data Missing

### ISSUE THREAD

**Issue by coingraham** [broderickhyman/albiondata-client#53]
Checked the example URL: https://www.albion-online-data.com/api/v2/stats/view/T4_BAG,T5_BAG?locations=Caerleon,Bridgewatch&qualities=2

Expecting buy data, but it's blank.

**Comment by magica5** [comment]
Albion Data Client isn't working altogether. The Client isn't picking up the location from the game since the big update.

**Comment by magica5** [comment]
Please see https://github.com/broderickhyman/albiondata-client/issues/52

**Comment by coingraham** [comment]
Closing, duplicate
