### ISSUE TITLE
T5 Relics, T7 Souls, and both T8 Souls & Relics are not returning results

### ISSUE THREAD

**Issue by XyyxShard** [broderickhyman/albiondata-client#6]
While attempting to pull prices, I found that I could not get results for T5 Relics, T7 Souls, T8 Relics, and T8 Souls no matter how many times I browse the market for those specific items with the client running. A few other items also appear to not be working, I will attempt to compile a list if necessary.

Example API request: https://www.albion-online-data.com/api/v1/stats/prices/T8_RELIC?locations=Caerleon%20Market

Returns: []

**Comment by broderickhyman** [comment]
Fixed on the server side, sometimes the client doesn't pick up the zone transitions unfortunately. So in order to fix this I am constantly updating the location of all item updates, not the best solution but it works for now.
