### ISSUE TITLE
Is possible to increase maximum reqs/min? (currently 300 reqs/5min was 180/min)

### ISSUE THREAD

**Issue by gkdekker** [broderickhyman/albiondata-client#61]
I'm using the data to identify best trades and also equilize prices among cities. Now I'm interested in identify best craft possibilities. Can u contact me plz?

**Comment by broderickhyman** [comment]
No, I am shutting down my servers. The public api was not built to handle that kind of load, you can run your own database if you need that many queries. Besides you can batch api calls for multiple items.
