### ISSUE TITLE
Import path should be "github.com/sirupsen/logrus", not "github.com/Sirupsen/logrus"

### ISSUE THREAD

**Issue by KateGo520** [broderickhyman/albiondata-client#63]
## Background
As [README](https://github.com/sirupsen/logrus/blob/v1.0.4/README.md) of logrus v1.0.4 said, `github.com/Sirupsen/logrus` has renamed to `github.com/sirupsen/logrus`, `github.com/Sirupsen/logrus` is the old path, so anything using it should be updated to import and require `github.com/sirupsen/logrus`.

> Some environments experienced problems with the upper-case variant, so the lower-case was decided. Everything using `logrus` will need to use the lower-case: `github.com/sirupsen/logrus`. Any package that isn't, should be changed.

But `broderickhyman/albiondata-client` still used the old path:
https://github.com/broderickhyman/albiondata-client/blob/master/Gopkg.toml#L2
```
[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.4"
```

## Solution
Replace all the import paths, change `"github.com/Sirupsen/logrus"` to `"github.com/sirupsen/logrus"`.
Where did you import it: https://github.com/broderickhyman/albiondata-client/search?q=github.com%2FSirupsen%2Flogrus&unscoped_q=github.com%2FSirupsen%2Flogrus

**Comment by KateGo520** [comment]
@walkeralencar  @broderickhyman  Could you help me review this issue? Thx :p

**Comment by walkeralencar** [comment]
@KateGo520 thx for share your ideas, i've fixed that in local, and will confirm if OK o patch.
