### ISSUE TITLE
When i run albiondata-client it shuts down after a few seconds

### ISSUE THREAD

**Issue by RecklessPudge** [broderickhyman/albiondata-client#64]
So i wanted to use a black market tool and it was recommended to download this, so i did. But when i tried to launch  albiondata-client it shut down after a few seconds. So i dug through my files a bit and saw this WinPcap

Operating system detected on registry: 8 - AMD64
True operating system (kernel.dll):    8 - AMD64
npptools.dll present on the system:    false
netnm.inf present on the system:       false
nmnt.sys present on the system:        false
I don't want to mess somemthing up in my laptop so i didn't do anything.

**Comment by RecklessPudge** [comment]
Starting albion data client, Version 0.0.30
  This is a third-party application and is in no way affiliated with sandbox interactive or albion online                           additional parimeters can listed by calling this file with the -h parimeter                                                                        Watching Albion process with PID ''12148''

**Comment by JeffreyNaval** [comment]
I was also experiencing this.

**Comment by Tyrben** [comment]
The only solution to me is to reinstall. (each time, it's a pain)

**Comment by LuccaPrado** [comment]
For people having it just shutting down, you guys have some VPN software installed on your computer?

I had some problems using WinPcap (With an sniffer software) after installing Checkpoint vpn, maybe something like that is happening.

**Comment by DancingWind** [comment]
Could this be the problem (terminal):

sc query npcap

SERVICE_NAME: npcap
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
