### ISSUE TITLE
Albiondata-client shutsdown

### ISSUE THREAD

**Issue by Makihuda** [broderickhyman/albiondata-client#69]
After i open the client and after the message "Watching Albion process with PID "13564"..." and it just closes. I tried reinstalling WinPcap, reinstalling the client and it still doesn't work

**Comment by Tyrben** [comment]
Certainly a clone of issue #64 . Go see it and thumb it up. And maybe close this one...

**Comment by Makihuda** [comment]
well i tried everything said there, but it didn't fix anything

**Comment by Tyrben** [comment]
Also a clone of issue #58

**Comment by Tyrben** [comment]
If it's a problem of WinPCap second use failure (like said in every other "shutdown issues", why not just resinstall it at every startup, automatically?
