### ISSUE TITLE
Front-end client

### ISSUE THREAD

**Issue by lifeiscontent** [broderickhyman/albiondata-client#7]
any interest in working on a front-end client? I'm a react dev, and I started building a mirror API of AO REST Endpoints using GraphQL and then searched GitHub and found your project.

https://graphqlbin.com/v2/9Q04SR

**Comment by broderickhyman** [comment]
Sorry I forgot to get back to you. The thought has crossed my mind.
There is a discord channel for these discussions, you can find the info in the 'Contact Us' on https://www.albion-online-data.com/
