### ISSUE TITLE
Cant building the project like in wiki

### ISSUE THREAD

**Issue by HpyCat** [broderickhyman/albiondata-client#72]
When use dep ensure - nothing happen

**Comment by LuccaPrado** [comment]
Can you please give a little more information on what happened?
I Suggest to template your issue like that:

What is happening:
Expected behavior:
Commands used:
Step to reproduce:
Description of your environment:

**Comment by LuccaPrado** [comment]
Some news @HpyCat?

**Comment by Tyrben** [comment]
@HpyCat 
There are 3 steps, Could you provide use the log of each of them, not only the last one?
* `go get -u github.com/golang/dep/cmd/dep`
* `brew install dep`
* `dep ensure`

On which system are you? MacOS I presume...
