### ISSUE TITLE
Migrate from WinPcap to NPcap?

### ISSUE THREAD

**Issue by broderickhyman** [broderickhyman/albiondata-client#73]

**Comment by Tyrben** [comment]
What a great idea.

https://nmap.org/npcap/vs-winpcap.html

> WinPcap has been the de facto standard library for packet capture and link-layer packet injection for over a decade. Many open source and commercial network tools use WinPcap for network access and filtering, but it has been unmaintained since 2013 and is no longer supported.
> 
> Npcap is the exciting and feature-packed update to the venerable WinPcap packet capture library. Building on the successful WinPcap legacy, Npcap brings increased speed, security, and Windows 10 support. All of WinPcap's packet capture and injection features are included, with a few great additions like raw 802.11 frame capture. Still wondering if Npcap is right for you?

Will it still be possible to run under linux?

**Comment by LuccaPrado** [comment]
@Tyrben 
> 
> Will it still be possible to run under linux?

With NPcap specifically, no. 
But, the NPCap is based on [LibPCap](https://www.tcpdump.org/), so even if is decided to use NPcap on windows, and on linux use LibPCap there wouldn't be so much work (I guess) to use LibPCap on unix platforms and NPcap on windows.

**Comment by Tyrben** [comment]
No problem installing libpcap-dev (package name may vary on other distro)

> apt get libpcap-dev
> go build albiondata-client
