### ISSUE TITLE
New to everything

### ISSUE THREAD

**Issue by Filledcake** [broderickhyman/albiondata-client#74]
Im very new to coding and GitHub and was just wondering if I could get some help. Im just trying to implement prices into excel. I have been trying to use the Web Source Albion2D after I refresh and update the prices using the Albion Data Project program. The Web Source is just very inconsistent where sometimes the proper graph won't load and it seems to never update or refresh the prices. I was just wondering if theres another way to get the prices into an excel sheet that are able to be updated. All of this coding is quite foreign to me and Im trying to learn. Any help would be greatly appreciated.

**Comment by samhine** [comment]
There's a section on the data page https://www.albion-online-data.com/ dedicated to grabbing the data into an Excel/Sheets spreadsheet. 

The basic solution is to find a method to query the API from inside (which can be achieved using one of the linked libraries), and formatting into graphable data there.

**Comment by broderickhyman** [comment]
If you need more help you might be able to find someone willing on our discord channel: https://discord.gg/TjWdq24
