### ISSUE TITLE
Add Avalonian portals

### ISSUE THREAD

**Issue by Tyrben** [broderickhyman/albiondata-client#75]
It's more like a question, because I can't have the info.
Are the map data absorbed by the albiondata-client?
It is possible to do some requests to the data server about Avalonian portals?

I see this "events" in the source code:
* evNewPortalEntrance
* evNewPortalExit

But this is tracked when the user goes through a portal, isn't it?
I'm interested in gathering basic portal info of the mini map: which portal are active on the current map...

---
Edit
The ROAM project doesn't use albiondata. It has its own manual input on a webpage.

Could the feed of albiondata-client include the portals position and duration in a near future ?

Do I have to look into `operation_get_cluster_map_info.go` ?

---
Edit2
There is a warning to doing that... but we all know branches exist for that...
https://forum.albiononline.com/index.php/Thread/135576-Roads-of-Avalon-Mapping-GPS-Tools/

**Comment by broderickhyman** [comment]
I will not be adding this as it is directly against the TOS
