### ISSUE TITLE
Have the requests per IP been extremely reduced?

### ISSUE THREAD

**Issue by Triky313** [broderickhyman/albiondata-client#78]
For some time now I have been getting an error message after 3-4 API item price requests. (TooManyRequestsException)

Have the requests per IP been extremely reduced here?
My tool is as good as unusable for Price comparisons.

My tool: https://github.com/Triky313/AlbionOnline-StatisticsAnalysis

**Comment by broderickhyman** [comment]
No, it is still at 180 per 1 minute and 300 per 5 minutes. You can see different data in the response headers like so:
```
X-Rate-Limit-Limit: 5m
X-Rate-Limit-Remaining: 227
X-Rate-Limit-Reset: 2021-01-29T03:46:03.8421074Z
```

**Comment by Triky313** [comment]
Hmm okay, I'll check again whether something is wrong in my tool and there are too many requests.

Thanks for the answer. :)
