### ISSUE TITLE
Albion DataClient on GeForce NOW

### ISSUE THREAD

**Issue by ZackNCN** [broderickhyman/albiondata-client#79]
Hello AODP developers

I would like to ask if there is any way to make your executable search for GeForce NOW instead of Albion Online to be able to use it while playing albion with it.

Thank you very much
ZackNCN

**Comment by GeroinEXP** [comment]
> Hello AODP developers
> 
> I would like to ask if there is any way to make your executable search for GeForce NOW instead of Albion Online to be able to use it while playing albion with it.
> 
> Thank you very much
> ZackNCN

I think it's impossible. 
Because in fact, you get a live broadcast, and no packages go to you.

**Comment by broderickhyman** [comment]
Correct, this is going to be impossible
