### ISSUE TITLE
Adding new events and operations

### ISSUE THREAD

**Issue by Triky313** [broderickhyman/albiondata-client#80]
Does anyone know how to get the codes? Wireshark or what do you work with?

I would like to update the events, a lot has changed since the last major update.

**Comment by cafade** [comment]
For the record, I am personally not a contributor to the project. But as far as I know, the project uses [photon spectator](https://github.com/broderickhyman/photon_spectator) to listen for the data sent and received by the albion client. 

Every message is handled in this switch case: [client/listener.go#L197](https://github.com/broderickhyman/albiondata-client/blob/master/client/listener.go#L197) inside the file [albiondata-client/client/listener.go](https://github.com/broderickhyman/albiondata-client/blob/master/client/listener.go). The messages are classified in operation requests, operation responses, or events.

Then for example, depending on the operation request code this function called _decodeRequest_: [client/decode.go#L13](https://github.com/broderickhyman/albiondata-client/blob/master/client/decode.go#L13) triggers the appropriate code. This function uses the interface: [albiondata-client/client/operations.go](https://github.com/broderickhyman/albiondata-client/blob/master/client/operations.go) and the equivalent structure for the string/code match of each operation: [albiondata-client/client/operationtype_string.go](https://github.com/broderickhyman/albiondata-client/blob/master/client/operationtype_string.go).

The codes are found in the map structure for the messages with the number 253. For example the map structure for the operation _opHarvestStart_ printed when debugging is enabled is:

`OperationRequest: [46]opHarvestStart - map[0:32876289 1:6369 2:-1 253:46 255:1]`

Which shows us that the code for the operation _opHarvestStart_ is 46. Just like this line says it is: [client/operationtype_string.go#L57](https://github.com/broderickhyman/albiondata-client/blob/master/client/operationtype_string.go#L57)

The same goes for the events in: [client/listener.go#L220](https://github.com/broderickhyman/albiondata-client/blob/master/client/listener.go#L220), then they get decoded by: [client/decode.go#L79](https://github.com/broderickhyman/albiondata-client/blob/master/client/decode.go#L79); using [https://github.com/broderickhyman/albiondata-client/blob/master/client/events.go](https://github.com/broderickhyman/albiondata-client/blob/master/client/events.go) and [https://github.com/broderickhyman/albiondata-client/blob/master/client/eventtype_string.go](https://github.com/broderickhyman/albiondata-client/blob/master/client/eventtype_string.go).

I am sure there is a better way to check for the updated operations and event codes that I don't know of, but you can check for them by running Albion Data Client with the arguments _-debug_, _-operations_, and _-events_ then see what comes up. You could also add the argument _-ignore-decode-errors_ to filter out unrelated data. i.e:

`<albion-data-client executable> -debug -ignore-decode-errors -operations <op-number>, <op-number> -events <ev-number>, <ev-number>`

or for every operation and event at the same time with just:

`albion-data-client executable> -debug -ignore-decode-errors`

**Comment by Triky313** [comment]
Thank you.
In fact, I've been using the Debug Console for a while.

I wonder who made all the names out?
The code numbers are clear to me, but the names appear again and again in several projects and I have also adopted them.

I assume that someone has thought of the names at some point.

**Comment by cafade** [comment]
> Thank you.
> In fact, I've been using the Debug Console for a while.
> 
> I wonder who made all the names out?
> The code numbers are clear to me, but the names appear again and again in several projects and I have also adopted them.
> 
> I assume that someone has thought of the names at some point.

No problem. I got no idea where the names come from, maybe from [this](https://github.com/broderickhyman/ao-bin-dumps) project? Or from another similar one I would guess. Anyway, hope you have any luck finding out.

**Comment by broderickhyman** [comment]
@Triky313 @cafade The event and operation names used to be available directly in the decompiled code in their original enum structure. This has since changed and now it is almost impossible to get them from the code or in any automatic fashion. We are back to reverse engineering by watching the traffic. If you want we can discuss on discord if you still want to move forward.
