### ISSUE TITLE
Albion data client is broken

### ISSUE THREAD

**Issue by zhonzhih** [broderickhyman/albiondata-client#83]
Recently, there have been problems with the albion data. A few days ago, I couldn't get any information from the database. Now, when trying to update prices in the database using the client, i have error like on a screen.

- 
![photo_2021-05-24_19-24-37](https://user-images.githubusercontent.com/84732182/119377359-b3706980-bcc5-11eb-9c8e-2786f84029f1.jpg)

**Comment by raspher** [comment]
Duplicate, see #33 #85

**Comment by broderickhyman** [comment]
Closing as duplicate of #85
