### ISSUE TITLE
No prices are returned from the API

### ISSUE THREAD

**Issue by nicolaipischel** [broderickhyman/albiondata-client#86]
I'm unsure wether this is really a bug but when I query the albion-online-data api for example this one:

[https://albion-online-data.com/api/v2/stats/prices/T4_BAG,T4_BAG.json?locations=Caerleon,Bridgewatch&qualities=2](https://albion-online-data.com/api/v2/stats/prices/T4_BAG,T4_BAG.json?locations=Caerleon,Bridgewatch&qualities=2)

The price is always zero. I've tried it with multiple different items but it seems that something isn't right there.

I've also tried looking up the same items on albion2d but it is the same there.

Can you explain me why it behaves like this? was something in the game changed so the dataclients are no longer providing data to the API?

**Comment by luis815** [comment]
As per #33 (Scroll down, not the actually issue post)

> @broderickhyman posted on the discord server: Someone or some people hammered the server with new data and it capped at 100% CPU load. Broderick turned off new data and set it to read only (data from 12th May) until he's got the time to take a deeper look at it.
> You probably need to set up a private server to ingest data in the mean time.

So the server is essentially down, hence why services across the board are not working.

**Comment by luis815** [comment]
Actually, an announcement from June 15 indicates that the server will be back online by "the end of this weekend".

**Comment by raspher** [comment]
server is back, prices are available, seems solved :)
