### ISSUE TITLE
How to configure nats for albion data

### ISSUE THREAD

**Issue by noobcoderzzz** [broderickhyman/albiondata-client#9]
hello, can i know how to create the nats server for sending albion data locally? i have install nats server and edit the albiondata client to send data to my nats server but when i dump to sql i dont see anything. thank you.

**Comment by broderickhyman** [comment]
You need to run [albiondata-deduper-dotNet](https://github.com/broderickhyman/albiondata-deduper-dotNet) on the nats server. This takes the raw item updates and filters them to single updates
