### ISSUE TITLE
The operation code is somehow changed.

### ISSUE THREAD

**Issue by MysticCoss** [broderickhyman/albiondata-client#93]
I after the new season update the operation code is changed in someway. 
For example: Operation code 35 is change cluster previously, but now it's 36
Please notice and update it if needed

**Comment by DonnaldBelen** [comment]
Hello there, the black market scanning was affected by this but the regular market was not.

**Comment by MysticCoss** [comment]
They added something that causes everything shifted by 1. i dont know what it is

**Comment by mahhov** [comment]
Actually, it's a bit more complicated than a simple shift by 1:

Join instance, 2 -> 2 (unchanged)
Moving your character changed from, 21 -> 22
Zone change 35 -> 36
Opening loot/chest, 39 -> 40
Closing loot/chest, 40 -> 41
Auction house sell orders, 78 -> 79
Auction house buy orders, 79 -> 80
Auction house graph, 92 -> 93
Inspecting a player, 139 -> 140
/say, 188 -> 190
Entering a dungeon, 234 -> 235

Most of these are a shift of 1, but /say changed by 2.
So one possibility is they added something between 3 and 21, added something between 141 and 189, and removed something between 191 and 234.

**Comment by MysticCoss** [comment]
@mahhov can you show me how can i check it myself when those codes are changed again?

**Comment by mahhov** [comment]
@MysticCoss 
E.g., add a print statement whenever you see the code 190, then do /say in the game client, and observe your print statement occurs and the data associated with it includes whatever text you said.

**Comment by mahhov** [comment]
@phendryx yes, I had to do it manually. It helps that the codes tend to be +/- 10 of the original values; and that the message formats are unchanged, just the code has changed; so we know what the message will look like and the approximate code. 

I have some of the new data codes for today's update:

**Request messages:**
- 187: chatSay
- 22: move
- 234: enterDungeon
- 137: inspectRequest
- 91: auctionGraphRequest
- 77: auctionSellOrdersRequest
- 78: auctionBuyOrdersRequest
- 40: openLoot
- 41: closeLoot

**Response messages:**
- 2: join
- 36: zoneChange
- 137: inspectResponse
- 91: auctionGraph
- 77: auctionSellOrders
- 78: auctionBuyOrders

**Event messages:**
- 1: leave
- 6: healthUpdate
- 80: regenerationHealthChanged
- 26: newCharacter
- 130: characterStats
- 10: buffChange
- 79: characterEquipmentChanged
- 256: gainedSilver
- 71: updateSilver
- 299: foundDungeon
- 111: newMob
- 371: newShrine
- 372: updateShrine
- 255: inCombat
- 23: inventoryChange
- 423: mobList
- 64: chat
- 254: zonePopulation


Mob/player position messages (which have their own special format have changed from special code 2 to 3.
