### ISSUE TITLE
History data Corrupted and not updating

### ISSUE THREAD

**Issue by Marck1997** [broderickhyman/albiondata-client#97]
Hello, 
I've noticed that the history data is not updating at all and old data is somehow corrupted too.
Why is this happening?

**Comment by phendryx** [comment]
History data was not being sent to the server over the last month. Previous to that, we know there was bad data being sent to us. As of tonight, there is a fix pushed out to fix history data being sent to the server and over the old/bad data won't matter.

**Comment by Marck1997** [comment]
Really tnx for the effort in fixing the problem and to,  overall, take care of this project ! 
It is really a lot appreciated!
You are doing an amazing job here!
